development:
  dialect: postgres
  database: coke2_development
  user: postgres
  password: supersecretpassword
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:supersecretpassword@127.0.0.1:5432/coke2_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:supersecretpassword@127.0.0.1:5432/coke2_production?sslmode=disable"}}